<center><p float="center">

  <img src="https://mma.prnewswire.com/media/1458111/Great_Learning_Logo.jpg?p=facebook" width="200" height="100"/>
</p></center>

<h1><center>Introduction to Python</center></h1>
<center>Variables, Datatypes, Data Structures, Conditional Statements, Loops, Functions</center>

# Case Study: ShopSmart Retail Analysis

### **Business Context**

**ShopSmart** is a dynamic and growing retail chain, operating in multiple locations across the country. With a diverse range of products spanning various categories, SmartShop caters to everyday consumer needs, offering groceries, electronics, apparel, household items, and more. The company prides itself on its customer-centric approach, competitive pricing, and a convenient shopping experience. They are one of the biggest player in the retail market. They are collecting details about the product, sales and the rating provided by the customers.


### **Objective**
You have been hired as a Data Scientist to handle and organize and analyze the data. You are responsible to organise the data so that, it will be easily accessible and help the company to use the data for further data analytics.

| Product_ID | Product_Name | Category | Price | Quantities_Sold | Customer_ID | Rating
| --- | --- | --- | --- | --- | --- | --- |
| P1001 | Organic Apple | Grocery | 50 | 30 | C5001 | 4.5
| P1002 | Whole Wheat Bread | Grocery |30 | 15 | C5002 | 4.0
| P2001 | Bluetooth Headphone | Electronics | 1000 | 5 | C5003 | 4.2
| P2002 | Smart Watch | Grocery | 800 | 7 | C5004 | 4.6

## 1. Organizing data in appropriate format

## Context:
ShopSmart have a dataset containing information about products, sales, and customer interactions. The data includes fields like

**Product_id, Product_Name, Category, Price, Quantity_Sold, Date_of_Sale, Customer_ID, and Rating.**


Let's store the information in variables and work over it

**1. Variables**
A variable in Python is a reserved memory location to store values. In other words, a variable in a program gives data to the computer for processing.

**2. Data Types**

Python supports several built-in data types that allow you to store different kinds of data.

Python has various data types including:

**Integers**: Whole numbers, e.g., 5, 100.

**Floats**: Numbers with a decimal point, e.g., 3.14, 2.0.

**Strings**: Sequence of characters, e.g., "Hello", 'Python'.

**Booleans**: True or False.

**Lists**: Ordered, mutable collections of items, e.g., [1, 2, 3], ['a', 'b', 'c'].

**Tuples**: Ordered, immutable collections, e.g., (1, 2, 3).

**Dictionaries**: Key-value pairs, e.g., {'name': 'Alice', 'age': 25}.

**Sets**: Unordered collection of unique elements, e.g., {1, 2, 3}.

Let's try to create a variable to store a feature **Product_id*

In [ ]:
Product_id = 'pid-01'  # A variable is created with the name Product_id and a value 'pid-01' is stored in the variable

Let's print the variable now

In [ ]:
print('The Product ID of the first product is',Product_id) #to display the value of the variable or a statement

The Product ID of the first product is pid-01

Let's store other product ids in the same manner.

In [ ]:
# Creating multiple variables to store unique product id
Product_id1 = 'pid-01'
Product_id2 = 'pid-02'
Product_id3 = 'pid-03'
Product_id4 = 'pid-04'
Product_id5 = 'pid-05'

Variables are used to store any type of data.
* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
          Correct: myVar, _myVar, var123
          Incorrect: 1myVar, 123var

* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _)
          Correct: my_var, var123, a_b_c
          Incorrect: my-var, var@123, a*b*c

* Variable names are case-sensitive (age, Age and AGE are three different variables)
          age, Age, and AGE are three different variables. For example:
          These conditions help ensure that variable names are clear, unambiguous, and follow a consistent convention in programming.

In [ ]:
age = 25
Age = 30
AGE = 35

print(age)  # Output: 25
print(Age)  # Output: 30
print(AGE)  # Output: 35

25
30
35


* Variable names cannot be the same as reserved words (keywords) in the language.In Python, you cannot use if, else, for, while, etc., as variable names
          Incorrect: def = 10, class = 'hello'
          Correct: my_def = 10, my_class = 'hello'


But if we proceed this way, we will have to create multiple variables to store a single feature, which is not an ideal way to store or access data. What if we try to store this data as a list? We will see this later

## 2. Organizing and querying the data

### List

**What is a List?**
> A list in Python is an ordered group of items or elements which are stored in a single variable.

**How do we define a list?**
> Lists are created using square brackets, and the elements are seperated by comma.
```
list_name = [element1, element2,...., element_n]
```

In [ ]:
Product_id = ['pid-0001', 'pid-0002', 'pid-0003', 'pid-0004', 'pid-0005' 'pid-0006', 'pid-0007', 'pid-0008', 'pid-0009', 'pid-0010',] # elements of lists are seperated by comma

## Let's print the list to see if this works
print("Product id:",Product_id)

Product id: ['pid-0001', 'pid-0002', 'pid-0003', 'pid-0004', 'pid-0005pid-0006', 'pid-0007', 'pid-0008', 'pid-0009', 'pid-0010']

Let's see what is the data type of `Product_id`

In [ ]:
type(Product_id)

list

* These work well and now we can store similar features by creating only single data element

**Q1. Try creating lists for Product_Name, Category, Price, Quantity_Sold, Date_of_Sale, Customer_id, and Rating**

All food items are in lot of 10 units

In [ ]:
# list for storing product names.
Product_name = ['earphones', 'charger', 'apple', 'potato', 'sunscreen', 'milk', 'bread','cold drink', 'egg', 'banana']

 # list for storing product categories.
Category = ['electronics', 'electronics', 'food', 'food', 'cosmetics', 'food', 'food','beverage','food','food']

# list to store the product prices in INR.
Price = [1000, 600, 250, 100, 60, 450, 500, 100, 70, 100]

# list to store the quantities sold.
Quantity_sold = [500, 300, 80, 100, 120, 100, 80, 800, 60, 30]

#list to store the customers id
Customer_id =  ['cid 111', 'cid 112', 'cid 113', 'cid 114', 'cid 115', 'cid 116', 'cid 117', 'cid 118', 'cid 119', 'cid 120']

# list to store the ratings
Rating = [3, 3, 5, 4, 3, 5, 4, 4, 3, 3]

**Q2. Try printing the elements from other lists**

In [ ]:
print("Product_name:", Product_name)
print("Category:", Category)
print("Price:", Price)
print("Quantity_sold:", Quantity_sold)
print("Customer_id:", Customer_id)
print("Rating:", Rating)

Product_name: ['earphones', 'charger', 'apple', 'potato', 'sunscreen', 'milk', 'bread', 'cold drink', 'egg', 'banana']
Category: ['electronics', 'electronics', 'food', 'food', 'cosmetics', 'food', 'food', 'beverage', 'food', 'food']
Price: [1000, 600, 250, 100, 60, 450, 500, 100, 70, 100]
Quantity_sold: [500, 300, 80, 100, 120, 100, 80, 800, 60, 30]
Customer_id: ['cid 111', 'cid 112', 'cid 113', 'cid 114', 'cid 115', 'cid 116', 'cid 117', 'cid 118', 'cid 119', 'cid 120']
Rating: [3, 3, 5, 4, 3, 5, 4, 4, 3, 3]

Great! now as the lists are created, let's try to fetch some data.

Let's say we want to get all the details of the product whose id is "pid-0002"

**How are Lists indexed?**
> List items are ordered and their indexing starts from 0 from beginning.
Let's say the elements stored in the index are a, b, c and d. Then the index will be as follows.

![index.png]()

In [ ]:
# To get data of pid-0002, we need to first find the index of the same.
pos = Product_id.index('pid-0002')  # index() is used to fetch the index of the value mentioned
print(pos)  # This will print the index of 'pid-0002'

1

In [ ]:
## Now that we know the index, let's call the value stored at the index for all the lists.
# Print information about the product at the found index
print(f"Product ID: {Product_id[pos]}")
print(f"Product Name: {Product_name[pos]}")
print(f"Category: {Category[pos]}")
print(f"Price: {Price[pos]}")
print(f"Quantity Sold: {Quantity_sold[pos]}")
print(f"Customer ID: {Customer_id[pos]}")
print(f"Rating: {Rating[pos]}")

Product ID: pid-0002
Product Name: charger
Category: electronics
Price: 600
Quantity Sold: 300
Customer ID: cid 112
Rating: 3

**Methods in list**

**Try getting the number of products in the above list**

In [ ]:
num_products = len(Product_name)
print(f"Number of products: {num_products}")

Number of products: 10

**Q3. Print the number of categories in list.**

In [ ]:
# Get the number of categories
num_categories = len(Category)

# Print the number of categories
print(f"Number of categories: {num_categories}")

Number of categories: 10

**Find the minimum and maximum price of products in list.**

In [ ]:
# minimum price
min_price = min(Price)
print('The minimum price is Rs.' + str(min_price))

# maximum price
max_price = max(Price)
print('The maximum price is Rs.' + str(max_price))

The minimum price is Rs.60
The maximum price is Rs.1000

**Q4. Find the min and max quantity sold**

In [ ]:
# minimum price
min_qty = min(Quantity_sold)
print('The minimum qty sold is ' + str(min_qty))

# maximum price
max_qty = max(Quantity_sold)
print('The maximum qty sold is ' + str(max_qty))

The minimum qty sold is 30
The maximum qty sold is 800

**Print the last product in the list**

In [ ]:
# indexing to get the last product in list

last_product = Product_name[9]

# Print the last product
print(f"Last product: {last_product}")

Last product: banana

Is there any other way to do the same thing?

In [ ]:
# Get the last product using indexing

print(Product_name[-1])

banana

**Print first 5 products in list**

In [ ]:
# Get the first 5 products using indexing
first_five_products = Product_name[0:5]

# Print the first 5 products
print(f"First 5 products: {first_five_products}")

First 5 products: ['earphones', 'charger', 'apple', 'potato', 'sunscreen']

**Print the last 3 products in list**

In [ ]:
# indexing to get the last 3 product in list
print(Product_name[-3:])

['cold drink', 'egg', 'banana']

**Remove egg from the list**

In [ ]:
# Remove egg from list
Product_name.remove('egg')
print(Product_name)

['earphones', 'charger', 'apple', 'potato', 'sunscreen', 'milk', 'bread', 'cold drink', 'banana']

In [ ]:
# Check if 'egg' is still in the list. we will get ValueError: 'egg' is not in list

#Product_name.index("egg")


methods use to add elements to a list in Python:

**1. Appending an Item to a List:**

To add an item to the end of a list in Python, you can use the append() method. Here's an example:
*italicized text*

In [ ]:
Product_name.append('Cheese')
print(Product_name)

['earphones', 'charger', 'apple', 'potato', 'sunscreen', 'milk', 'bread', 'cold drink', 'banana', 'Cheese']

**2. Insert**

insert(index, item): Inserts item at the specified index in the list. Elements to the right of this index are shifted to accommodate the new element.**bold text**

In [ ]:
# Example
Product_name.insert(2, 'juice')  # Insert 'juice' at index 2
print(Product_name)

['earphones', 'charger', 'juice', 'apple', 'potato', 'sunscreen', 'milk', 'bread', 'cold drink', 'banana', 'Cheese']

### Tuple

A tuple is an ordered collection of elements.

>It is immutable, meaning once a tuple is created, its elements cannot be changed, added, or removed.

>Tuples are defined by enclosing elements in parentheses ().

Let's see the example to demonstrate the basics of a tuple in Python. We'll create a single tuple for one product, and then perform a couple of basic operations on it:

Let's create one more sales data and use that for querying details.

In [ ]:
# Single product details
product_name = 'bluetooth earphones'
category = 'electronics'
price = 1500
quantity_sold = 200
customer_id = 'cid 111'
rating = 4

**We can use round brackets to create tuple.**

In [ ]:
# Creating a tuple for this product
product_tuple = (product_name, category, price, quantity_sold, customer_id, rating)

print(product_tuple)

print(type(product_tuple))

('bluetooth earphones', 'electronics', 1500, 200, 'cid 111', 4)
<class 'tuple'>

**Accessing the elements in tuple**

Accessing elements in tuple is similar to the accessing elements in lists that we just saw above.


![index.png]()

In [ ]:
# Accessing elements in the tuple
print("Product Name:", product_tuple[0])
print("Category:", product_tuple[1])
print("Price:", product_tuple[2])

Product Name: bluetooth earphones
Category: electronics
Price: 1500

**Tuple Methods**

>Tuples have fewer built-in methods than lists due to their immutability.

>Common methods include
>> count(): to count occurrences of an element

>> index(): to find the index of an element.

>> len(): to calculate the length of tuple

In [ ]:
# Count of tuple
print("The count of electronics in tuple is :", product_tuple.count('electronics'))

# index of tuple
print("The index of the tuple with price 1500 is :", product_tuple.index(1500))

# Length of the tuple
print("Number of elements in tuple:", len(product_tuple))

The count of electronics in tuple is : 1
The index of the tuple with price 1500 is : 2
Number of elements in tuple: 6

### Dictionary

A dictionary in Python is a collection of key-value pairs. It is a versatile, mutable data type that allows you to store and manage data in a way similar to a real-life dictionary.

Dictionary & Operations Using Python Dictionaries

In [ ]:
# 1. Creating a dictionary
products = {
    'earphones': {'category': 'electronics', 'price': 1000, 'quantity_sold': 500},
    'apple': {'category': 'food', 'price': 250, 'quantity_sold': 80},
    'sunscreen': {'category': 'cosmetics', 'price': 60, 'quantity_sold': 120}
}

In [ ]:
#checking the type of *products*

type(products)

dict

**Creating a dictionary**

  You can create a dictionary by placing a comma-separated list of key-value pairs within curly braces {}, with a colon : separating the keys and values.

In [ ]:
# 1. Creating a dictionary
products = {
    'earphones': {'category': 'electronics', 'price': 1000, 'quantity_sold': 500},
    'apple': {'category': 'food', 'price': 250, 'quantity_sold': 80},
    'sunscreen': {'category': 'cosmetics', 'price': 60, 'quantity_sold': 120}
}

**Accessing Values of dictionary**

This shows how to retrieve specific information from a dictionary. in below code, the price of earphones is accessed using nested keys. This is common in dealing with structured data where one key leads to another set of data.

In [ ]:
# Accessing values
print("Price of earphones:", products['earphones']['price'])

Price of earphones: 1000

**Adding and Modifying Elements**

Here, we are demonstrating how to add a new key-value pair to a dictionary and how to modify an existing value. This is crucial in dynamic data handling where the contents of a dictionary need to be updated or expanded.

In [ ]:
#Adding and modifying elements
products['charger'] = {'category': 'electronics', 'price': 600, 'quantity_sold': 300}  # Add new item
products['apple']['price'] = 200  # Modify existing item

print(products)

{'earphones': {'category': 'electronics', 'price': 1000, 'quantity_sold': 500}, 'apple': {'category': 'food', 'price': 200, 'quantity_sold': 80}, 'sunscreen': {'category': 'cosmetics', 'price': 60, 'quantity_sold': 120}, 'charger': {'category': 'electronics', 'price': 600, 'quantity_sold': 300}}

**Removing Elements**

This part of the code illustrates how to remove items from a dictionary. One method used is the del statement, and another is the pop method, which also returns the value of the removed item.

In [ ]:
#Removing elements
# Remove 'sunscreen' from the dictionary
del products['sunscreen']  # Remove item

# Remove 'charger' from the dictionary and get the quantity sold
charger_sold = products.pop('charger')['quantity_sold']  # Remove and get quantity sold of charger

print(charger_sold)
print(products)

300
{'earphones': {'category': 'electronics', 'price': 1000, 'quantity_sold': 500}, 'apple': {'category': 'food', 'price': 200, 'quantity_sold': 80}}

**Keys, Values, and Items**

 This section shows how to retrieve lists of keys, values, or key-value pairs from a dictionary. These methods are essential for examining the structure and contents of a dictionary.

In [ ]:
#Keys, Values, and Items
product_names = products.keys() #retrieve all keys
product_details = products.values() #retrieve all values of every key
all_products = products.items() #retrieve keys and values

print(product_names)
print(product_details)
print(all_products)

dict_keys(['earphones', 'apple'])
dict_values([{'category': 'electronics', 'price': 1000, 'quantity_sold': 500}, {'category': 'food', 'price': 200, 'quantity_sold': 80}])
dict_items([('earphones', {'category': 'electronics', 'price': 1000, 'quantity_sold': 500}), ('apple', {'category': 'food', 'price': 200, 'quantity_sold': 80})])

**Let's create one more dictionary and perform few other operations and methods of python**

In [ ]:
Sales_data = [
    {"Product_ID": "P1001", "Product_Name": "Organic Apple", "Category": "Groceries", "Price": 50, "Quantity_Sold": 30, "Customer_ID": "C5001", "Rating": 4.5},
    {"Product_ID": "P1002", "Product_Name": "Whole Wheat Bread", "Category": "Groceries", "Price": 30, "Quantity_Sold": 15, "Customer_ID": "C5002", "Rating": 4.0},
    {"Product_ID": "P2001", "Product_Name": "Bluetooth Headphones", "Category": "Electronics", "Price": 1500, "Quantity_Sold": 5, "Customer_ID": "C5003", "Rating": 4.2},
    {"Product_ID": "P1001", "Product_Name": "Organic Apple", "Category": "Groceries", "Price": 50, "Quantity_Sold": 50, "Customer_ID": "C5004", "Rating": 4.5},
     {"Product_ID": "P2002", "Product_Name": "Smart Watch", "Category": "Electronics", "Price": 800, "Quantity_Sold": 7, "Customer_ID": "C5004", "Rating": 4.6},
    {"Product_ID": "P3001", "Product_Name": "Yoga Mat", "Category": "Sporting Goods", "Price": 300, "Quantity_Sold": 10, "Customer_ID": "C5005", "Rating": 4.8},
    {"Product_ID": "P3002", "Product_Name": "Dumbbell Set", "Category": "Sporting Goods", "Price": 500, "Quantity_Sold": 8, "Customer_ID": "C5006", "Rating": 4.7},
    {"Product_ID": "P4001", "Product_Name": "Cotton T-Shirt", "Category": "Apparel", "Price": 200, "Quantity_Sold": 20, "Customer_ID": "C5007", "Rating": 4.3},
    {"Product_ID": "P4002", "Product_Name": "Jeans", "Category": "Apparel", "Price": 300, "Quantity_Sold": 12, "Customer_ID": "C5008", "Rating": 4.5},
   {"Product_ID": "P4002", "Product_Name": "Jeans", "Category": "Apparel", "Price": 300, "Quantity_Sold": 20, "Customer_ID": "C5007", "Rating": 4.5},
    {"Product_ID": "P5001", "Product_Name": "Running Shoes", "Category": "Footwear", "Price": 600, "Quantity_Sold": 9, "Customer_ID": "C5009", "Rating": 4.4},
    {"Product_ID": "P5002", "Product_Name": "Leather Wallet", "Category": "Accessories", "Price": 150, "Quantity_Sold": 11, "Customer_ID": "C5010", "Rating": 4.6}

]

In [ ]:
Sales_data

[{'Product_ID': 'P1001',
  'Product_Name': 'Organic Apple',
  'Category': 'Groceries',
  'Price': 50,
  'Quantity_Sold': 30,
  'Customer_ID': 'C5001',
  'Rating': 4.5},
 {'Product_ID': 'P1002',
  'Product_Name': 'Whole Wheat Bread',
  'Category': 'Groceries',
  'Price': 30,
  'Quantity_Sold': 15,
  'Customer_ID': 'C5002',
  'Rating': 4.0},
 {'Product_ID': 'P2001',
  'Product_Name': 'Bluetooth Headphones',
  'Category': 'Electronics',
  'Price': 1500,
  'Quantity_Sold': 5,
  'Customer_ID': 'C5003',
  'Rating': 4.2},
 {'Product_ID': 'P1001',
  'Product_Name': 'Organic Apple',
  'Category': 'Groceries',
  'Price': 50,
  'Quantity_Sold': 50,
  'Customer_ID': 'C5004',
  'Rating': 4.5},
 {'Product_ID': 'P2002',
  'Product_Name': 'Smart Watch',
  'Category': 'Electronics',
  'Price': 800,
  'Quantity_Sold': 7,
  'Customer_ID': 'C5004',
  'Rating': 4.6},
 {'Product_ID': 'P3001',
  'Product_Name': 'Yoga Mat',
  'Category': 'Sporting Goods',
  'Price': 300,
  'Quantity_Sold': 10,
  'Customer_ID': 'C5005',
  'Rating': 4.8},
 {'Product_ID': 'P3002',
  'Product_Name': 'Dumbbell Set',
  'Category': 'Sporting Goods',
  'Price': 500,
  'Quantity_Sold': 8,
  'Customer_ID': 'C5006',
  'Rating': 4.7},
 {'Product_ID': 'P4001',
  'Product_Name': 'Cotton T-Shirt',
  'Category': 'Apparel',
  'Price': 200,
  'Quantity_Sold': 20,
  'Customer_ID': 'C5007',
  'Rating': 4.3},
 {'Product_ID': 'P4002',
  'Product_Name': 'Jeans',
  'Category': 'Apparel',
  'Price': 300,
  'Quantity_Sold': 12,
  'Customer_ID': 'C5008',
  'Rating': 4.5},
 {'Product_ID': 'P4002',
  'Product_Name': 'Jeans',
  'Category': 'Apparel',
  'Price': 300,
  'Quantity_Sold': 20,
  'Customer_ID': 'C5007',
  'Rating': 4.5},
 {'Product_ID': 'P5001',
  'Product_Name': 'Running Shoes',
  'Category': 'Footwear',
  'Price': 600,
  'Quantity_Sold': 9,
  'Customer_ID': 'C5009',
  'Rating': 4.4},
 {'Product_ID': 'P5002',
  'Product_Name': 'Leather Wallet',
  'Category': 'Accessories',
  'Price': 150,
  'Quantity_Sold': 11,
  'Customer_ID': 'C5010',
  'Rating': 4.6}]

#### **Set**

What is a Set?
- A set in Python is an unordered collection of unique elements.
- Sets are defined by enclosing elements in curly braces {}, separated by commas
- Sets automatically remove duplicate values, ensuring all elements are unique.

In [ ]:
# You can create a set by listing elements inside curly braces {}.
# Example of creating a set
my_set = {"P1001", "P1002", "P1001", "P1003", "P1004"}

**Adding Elements**: Use the add() method to add a single element to a set.

In [ ]:
my_set.add("P1005")
print(my_set)

{'P1002', 'P1005', 'P1001', 'P1004', 'P1003'}

**Removing Elements**: Use the remove() or discard() method to remove an element from a set. discard() does not raise an error if the element is not present.

In [ ]:
my_set.remove("P1002")
print(my_set)

{'P1005', 'P1001', 'P1004', 'P1003'}

In [ ]:
my_set.discard("P1004")
print(my_set) # no error

{'P1005', 'P1001', 'P1003'}

**Set Operations**

- Union: Combines elements from two sets, excluding duplicates.
- Intersection: Returns elements common to both sets.
- Difference: Returns elements in one set but not the other.

In [ ]:
set1 = {"P1001", "P1002", "P1003"}
set2 = {"P1003", "P1004", "P1005"}
union_set = set1 | set2  # Using the | operator
intersection_set = set1 & set2  # Using the & operator
difference_set = set1 - set2  # Elements in set1 but not in set2

print("union_set", union_set)
print("intersection_set", intersection_set)
print("difference_set", difference_set)

union_set {'P1002', 'P1005', 'P1001', 'P1004', 'P1003'}
intersection_set {'P1003'}
difference_set {'P1001', 'P1002'}

### Boolean

What is Boolean?
- Boolean is a built-in data type in Python used to represent truth values: True and False.
- Booleans are primarily used for conditions and logical operations.
- The two boolean values in Python are True and False.

In [ ]:
# Comparison operators (==, !=, <, >, <=, >=) return boolean values based on the comparison result.
Price_1 = 5
Price_2 = 10
result = Price_1 < Price_2  # result will be True because 5 is less than 10
print(result)

True

### Looping Statements


In Python, looping is a fundamental concept that allows you to iterate over items in a collection, like a list or dictionary. The most common types of loops are for loops and while loops.

1. **for Loops**
A for loop is used for iterating over a sequence (such as a list, tuple, string, or any iterable object) and executing a block of code once for each element in the sequence.

In [ ]:
# Using a for loop to iterate over the Sales_data list
for product in Sales_data:
    print(product["Product_Name"])

Organic Apple
Whole Wheat Bread
Bluetooth Headphones
Organic Apple
Smart Watch
Yoga Mat
Dumbbell Set
Cotton T-Shirt
Jeans
Jeans
Running Shoes
Leather Wallet

**Q5. For each product in Sales_data, print the Product_Name, Category, and Price.**

In [ ]:
# Using a for loop to iterate over the Sales_data list
for product in Sales_data:
    product_name = product["Product_Name"]
    category = product["Category"]
    price = product["Price"]

    # Printing the product details
    print(f"Product name: {product_name}, Category: {category}, Price: {price}")

Product name: Organic Apple, Category: Groceries, Price: 50
Product name: Whole Wheat Bread, Category: Groceries, Price: 30
Product name: Bluetooth Headphones, Category: Electronics, Price: 1500
Product name: Organic Apple, Category: Groceries, Price: 50
Product name: Smart Watch, Category: Electronics, Price: 800
Product name: Yoga Mat, Category: Sporting Goods, Price: 300
Product name: Dumbbell Set, Category: Sporting Goods, Price: 500
Product name: Cotton T-Shirt, Category: Apparel, Price: 200
Product name: Jeans, Category: Apparel, Price: 300
Product name: Jeans, Category: Apparel, Price: 300
Product name: Running Shoes, Category: Footwear, Price: 600
Product name: Leather Wallet, Category: Accessories, Price: 150

**Range Function with for Loops**

- The range function is a built-in function in Python that generates a sequence of numbers from a start value to an end value.
- The range() function generates a sequence of numbers that is commonly used with for loops to iterate a specified number of times.

```
    for i in range(start, stop, step):
        Block of code to execute for each value of i in the range
```

**Print the first three Product_Names from Sales_data.**

In [ ]:
# Using a for loop with range function
for i in range(3):  # Loop through the first three elements
    print(Sales_data[i]["Product_Name"])

Organic Apple
Whole Wheat Bread
Bluetooth Headphones

**Q6. Print the first five categories from Sales_data.**

In [ ]:
# Using a for loop with range to print the first five product names
for i in range(5):  # Looping through the first two indices (0 and 1)
    print(Sales_data[i]["Category"])

Groceries
Groceries
Electronics
Groceries
Electronics

 **Iterating every two indices**

In [ ]:
for i in range(0, 10, 2): #  Iterating every two indices
    print(Sales_data[i]["Category"])

Groceries
Electronics
Electronics
Sporting Goods
Apparel

**While Loop**

A while loop is a common control flow statement in programming languages that allows a block of code to be repeatedly executed as long as a particular condition remains true. The basic syntax of a while loop is while (condition) { } where the condition is evaluated before each iteration of the block of code within the curly braces. If the condition is true, the block of code is executed; if the condition is false, the loop terminates and the program continues after the while loop.
- A while loop repeatedly executes a block of code as long as a specified condition is True.

In [ ]:
# Using a while loop to print the first two product names
i = 0  # Start from the first index
while i < 3:
    print(Sales_data[i]["Product_Name"])
    i += 1  # Increment the index

print(i) # i is not less than  3

Organic Apple
Whole Wheat Bread
Bluetooth Headphones
3

**Q7. Print the Product_Name of each item in Sales_data until the total price of all iterated products exceeds 10000.**

In [ ]:
total_price = 0  # Initialize total price
i = 0  # Initialize counter

while i < len(Sales_data) and total_price <= 10000:
    item = Sales_data[i]
    product_price = item["Price"] * item["Quantity_Sold"]
    total_price += product_price

    if total_price <= 10000:  # Check the total price before printing
        print(item["Product_Name"])

    i += 1  # Increment counter

Organic Apple
Whole Wheat Bread
Bluetooth Headphones

### Conditional Statements

>Conditional statements allow you to execute different blocks of code based on specified conditions.

> Conditional statements are an important part of decision-making in Python. Results are generated for the satisfied condition.

**If Else Conditional Statement**

> The if-else statement in Python is used for decision-making. The general syntax of an if-else statement is:
```
    if condition:
         Block of code to execute if condition is True
    else:
         Block of code to execute if condition is False
```
>It contains a body of code which runs only when the condition given in the if statement is true. If the condition is false, then the optional else statement runs which contains some code for the else condition.

**if-elif-else Statement**

- The elif statement allows you to check multiple conditions sequentially.
- It executes the block associated with the first True condition encountered. If no condition is True and an else block is provided, that block is executed.

```
    if condition1:
        Block of code to execute if condition1 is True
    elif condition2:
        Block of code to execute if condition1 is False and condition2 is True
    else:
        Block of code to execute if all conditions are False
```

**Check the category of the first product in the Sales_data list. If it's in the "Groceries" category, we'll print a message confirming that. If it's not, we'll print a different message.**

In [ ]:
# Accessing the first product
first_product = Sales_data[0]

# If-else statement to check category
if first_product["Category"] == "Groceries":
    print(f"The product {first_product['Product_Name']} is in the Groceries category.")
else:
    print(f"The product {first_product['Product_Name']} is not in the Groceries category.")

The product Organic Apple is in the Groceries category.

**Q9 Check if the last product's price is greater than 1000. If it is, we'll print a message stating that the product is expensive. Otherwise, we'll print a message indicating that the product is affordable.**

In [ ]:
# Set the price threshold
price_threshold = 1000

# Iterate through each product in sales_data and classify
for product in Sales_data:
    if product["Price"] > price_threshold:
        print(f"The product {product['Product_Name']} is expensive.")
    else:
        print(f"The product {product['Product_Name']} is affordable.")

The product Organic Apple is affordable.
The product Whole Wheat Bread is affordable.
The product Bluetooth Headphones is expensive.
The product Organic Apple is affordable.
The product Smart Watch is affordable.
The product Yoga Mat is affordable.
The product Dumbbell Set is affordable.
The product Cotton T-Shirt is affordable.
The product Jeans is affordable.
The product Jeans is affordable.
The product Running Shoes is affordable.
The product Leather Wallet is affordable.

In [ ]:
# Set the price threshold
price_threshold = 500

# Iterate through each product in sales_data and classify
for product in Sales_data:
    if product["Price"] > price_threshold:
        print(f"The product {product['Product_Name']} is expensive.")
    elif product["Price"] > 2*price_threshold:
        print(f"The product {product['Product_Name']} is very expensive.")
    else :
        print(f"The product {product['Product_Name']} is affordable.")

The product Organic Apple is affordable.
The product Whole Wheat Bread is affordable.
The product Bluetooth Headphones is expensive.
The product Organic Apple is affordable.
The product Smart Watch is expensive.
The product Yoga Mat is affordable.
The product Dumbbell Set is affordable.
The product Cotton T-Shirt is affordable.
The product Jeans is affordable.
The product Jeans is affordable.
The product Running Shoes is expensive.
The product Leather Wallet is affordable.

**Let's store the total sales for each product in a collection**

In [ ]:
# Initialize an empty dictionary to store total sales per product
total_sales_per_product = {}

# Iterate over each record in the sales data
for record in Sales_data:
    product_id = record["Product_ID"]
    sales_amount = record["Price"] * record["Quantity_Sold"]

    # If the product ID is already in the dictionary, add to its sales total
    if product_id in total_sales_per_product:
        total_sales_per_product[product_id] += sales_amount
    else:
        # Otherwise, initialize the total sales for this product ID
        total_sales_per_product[product_id] = sales_amount

# Display the total sales for each product
for product_id, total_sales in total_sales_per_product.items():
    print(f"Product ID {product_id} has total sales of: {total_sales:.2f} Rs")

Product ID P1001 has total sales of: 4000.00 Rs
Product ID P1002 has total sales of: 450.00 Rs
Product ID P2001 has total sales of: 7500.00 Rs
Product ID P2002 has total sales of: 5600.00 Rs
Product ID P3001 has total sales of: 3000.00 Rs
Product ID P3002 has total sales of: 4000.00 Rs
Product ID P4001 has total sales of: 4000.00 Rs
Product ID P4002 has total sales of: 9600.00 Rs
Product ID P5001 has total sales of: 5400.00 Rs
Product ID P5002 has total sales of: 1650.00 Rs

In [ ]:
total_sales_per_product

{'P1001': 4000,
 'P1002': 450,
 'P2001': 7500,
 'P2002': 5600,
 'P3001': 3000,
 'P3002': 4000,
 'P4001': 4000,
 'P4002': 9600,
 'P5001': 5400,
 'P5002': 1650}

**Q10. Calculate Total Quantities Sold for Each Product**

In [ ]:
# Dictionary to store total quantities sold for each product
total_quantities = {}

# Loop through each record and aggregate quantities
for record in Sales_data:
    product_name = record["Product_Name"]
    quantity_sold = record["Quantity_Sold"]

    if product_name in total_quantities:
        total_quantities[product_name] += quantity_sold
    else:
        total_quantities[product_name] = quantity_sold

# Display the total quantities for each product
for product, total_quantity in total_quantities.items():
    print(f"{product}: Total Quantity Sold = {total_quantity}")

Organic Apple: Total Quantity Sold = 80
Whole Wheat Bread: Total Quantity Sold = 15
Bluetooth Headphones: Total Quantity Sold = 5
Smart Watch: Total Quantity Sold = 7
Yoga Mat: Total Quantity Sold = 10
Dumbbell Set: Total Quantity Sold = 8
Cotton T-Shirt: Total Quantity Sold = 20
Jeans: Total Quantity Sold = 32
Running Shoes: Total Quantity Sold = 9
Leather Wallet: Total Quantity Sold = 11

**We can get the names of all products with a rating of 4.5 or higher one by one but that is a tidious process.**

**We can perform similar task using the looping and conditional statements.**

In [ ]:
# The sales data and prints the names of all products with a rating of 4.5 or higher.
for record in Sales_data:
    if record["Rating"] >= 4.5:
        print(record["Product_Name"], record["Rating"])

Organic Apple 4.5
Organic Apple 4.5
Smart Watch 4.6
Yoga Mat 4.8
Dumbbell Set 4.7
Jeans 4.5
Jeans 4.5
Leather Wallet 4.6

**Q11. Create a list containing the names of all products that have been sold in a quantity of 10 or more.**

In [ ]:
# Initialize an empty list to store the names of products
products_with_min_quantity = []

# Loop through each record in the sales data
for record in Sales_data:
    if record["Quantity_Sold"] >= 10:
        products_with_min_quantity.append(record["Product_Name"])

print("Products with a Minimum of 10 Units Sold:", products_with_min_quantity)

Products with a Minimum of 10 Units Sold: ['Organic Apple', 'Whole Wheat Bread', 'Organic Apple', 'Yoga Mat', 'Cotton T-Shirt', 'Jeans', 'Jeans', 'Leather Wallet']

In [ ]:
Sales_data[0].get("Category", 0)

'Groceries'

**We can use similar approach to find out the total sales value for each category.**

In [ ]:
# Calculate total sales for each category
category_sales = {}

# Iterate over each record in Sales_data
for record in Sales_data:
    category = record["Category"]
    sales = record["Price"] * record["Quantity_Sold"]
    # Update category_sales dictionary with total sales for each category
    #If category exists in category_sales, it returns its current value.
    #If not (category is not yet in category_sales), it returns 0 (the default value specified as the second argument).
    category_sales[category] = category_sales.get(category, 0) + sales

# Print results
for category, total_sales in category_sales.items():
    print(f"Category: {category}, Total Sales: {total_sales:.2f} Rs")

Category: Groceries, Total Sales: 4450.00 Rs
Category: Electronics, Total Sales: 13100.00 Rs
Category: Sporting Goods, Total Sales: 7000.00 Rs
Category: Apparel, Total Sales: 13600.00 Rs
Category: Footwear, Total Sales: 5400.00 Rs
Category: Accessories, Total Sales: 1650.00 Rs

**Identify products whose sales quantity has been increasing with each successive record.**

In [ ]:

trending_products = {}
consistent_increase = set()

# Code to also track product names
product_names = {}

for record in Sales_data:
    product_id = record["Product_ID"]
    product_name = record["Product_Name"]
    quantity_sold = record["Quantity_Sold"]

    # Keep track of product names
    product_names[product_id] = product_name

    # Check if product_id is already in trending_products
    if product_id not in trending_products:
        trending_products[product_id] = [quantity_sold]
    else:
        # Check if current quantity_sold is greater than the last recorded quantity
        if quantity_sold > trending_products[product_id][-1]:
            consistent_increase.add(product_id)
        trending_products[product_id].append(quantity_sold)

# Filter products and print the results
for product_id, sales_history in trending_products.items():
    if len(sales_history) > 1 and product_id in consistent_increase:
        print(f"Product name {product_names[product_id]} shows a general increasing trend in sales quantity.")

if not consistent_increase:
    print("No products found with a consistent increasing sales quantity trend.")

Product name Organic Apple shows a general increasing trend in sales quantity.
Product name Jeans shows a general increasing trend in sales quantity.

### Modular way of updating data - Functions

**What is a Function in Python?**

>In Python, a function is a block of instructions that performs a specific task.

**Why to use Functions?**
>Functions break the program into modular chunks which can be reused later. Functions are used to make the program more organized and manageable.

**How do we create a Function?**

The syntax for the function is:
```
def function_name(parameters):
	statement(s)
  return statement
```
An optional return statement is used to return value(s) from the function.

**What are parameters in Functions?**
>Parameters are variables through which we pass values to a function. Parameters are optional for function definition.

>Function Body: Contains the code to execute when the function is called, in this case, printing a greeting message.

>Calling a Function
To execute (or call) a function, you simply use its name followed by parentheses ( ), optionally passing arguments if the function expects them.

Now that we have total sales per product, let's calculate total sales value of a product using a user created function.

**Write a function called calculate_sale_price that takes two arguments: price and quantity, and returns the total price for that sale (which is simply the product of price and quantity).**

In [ ]:
def calculate_sale_price(price, quantity):
    return price * quantity

# Example Usage
sale_price = calculate_sale_price(500, 4)  # Assuming the price is Rs 2.5 and the quantity is 4
print(f"Total Price for the Sale: {sale_price} Rs")

Total Price for the Sale: 2000 Rs

**Write a function calculate_average_price that takes a list of prices and returns the average price.**

In [ ]:
def calculate_average_price(prices):
    return sum(prices) / len(prices) if prices else 0

print(calculate_average_price([100, 250, 600]))

316.6666666666667

**Calculate the total sales value for a given product.**

In [ ]:
def calculate_total_sales(product_id, sales_data):
    """
    :param product_id: The ID of the product
    :param sales_data: A list of dictionaries containing sales records
    :return: Total sales value of the product
    """
    total_sales = 0
    for record in sales_data:
        if record["Product_ID"] == product_id:
            total_sales += record["Price"] * record["Quantity_Sold"]
    return total_sales

# Example Usage
product_id_to_check = "P1001"  # Replace with the desired Product ID
total_sales_of_product = calculate_total_sales(product_id_to_check, Sales_data)
print(f"Total sales value of product {product_id_to_check}: {total_sales_of_product:.2f} Rs")

Total sales value of product P1001: 4000.00 Rs

**Q12. Calculates the final price of a product after applying a tax rate. The function should take the original price of the product and the tax rate as arguments and return the final price after tax.**

In [ ]:
def calculate_price_after_tax(original_price, tax_rate):
    """
    Calculate the final price of a product after applying a tax rate.

    :param original_price: The original price of the product
    :param tax_rate: The tax rate (as a percentage)
    :return: The final price after tax
    """
    tax_amount = original_price * (tax_rate / 100)
    final_price = original_price + tax_amount
    return final_price

# Example Usage
original_price = 100  # $100
tax_rate = 5  # 5% tax rate
final_price = calculate_price_after_tax(original_price, tax_rate)
print(f"The final price after applying a {tax_rate}% tax is: {final_price:.2f} Rs")

The final price after applying a 5% tax is: 105.00 Rs

**list comprehension to create a list of all products with a rating higher than 4.**

List comprehension is a concise way to create lists in Python. It allows you to define and populate a list using a single line of code, combining a for loop and an optional if condition.

In [ ]:
# List comprehension to get products with a rating higher than 4
products_high_rating = [record["Product_Name"] for record in Sales_data if record["Rating"] > 4.5]

print("Products with a rating higher than 4:", products_high_rating)

Products with a rating higher than 4: ['Smart Watch', 'Yoga Mat', 'Dumbbell Set', 'Leather Wallet']

**Q13. List All Products with a Minimum Quantity Sold**

In [ ]:
# Using list comprehension to get products with a quantity of 10 or more
products_with_min_quantity = [record["Product_Name"] for record in Sales_data if record["Quantity_Sold"] >= 10]

print("Products with a Minimum of 10 Units Sold:", products_with_min_quantity)

Products with a Minimum of 10 Units Sold: ['Organic Apple', 'Whole Wheat Bread', 'Organic Apple', 'Yoga Mat', 'Cotton T-Shirt', 'Jeans', 'Jeans', 'Leather Wallet']

**Lambda Function**

Lambda functions in Python are small anonymous functions defined with the lambda keyword. They can take any number of arguments, but can only have one expression. Lambda functions are often used for concise operations that don't require the full syntax of a regular function.

**Using a lambda function, filter and list all products from Sales_data that have a price higher than 500 Rs and a quantity sold less than 10.**

In [ ]:
# Use filter with a lambda function to find products meeting the criteria
high_price_low_sales = filter(lambda x: x['Price'] > 500 and x['Quantity_Sold'] < 10, Sales_data)

# Print the product details
for product in high_price_low_sales:
    print(f"{product['Product_Name']} (Price: {product['Price']}, Quantity Sold: {product['Quantity_Sold']})")

Bluetooth Headphones (Price: 1500, Quantity Sold: 5)
Smart Watch (Price: 800, Quantity Sold: 7)
Running Shoes (Price: 600, Quantity Sold: 9)

**How do you use a lambda function with map to calculate the total sales for all products in the "Electronics" category in Sales_data?**

In [ ]:
# Filter out products in the "Electronics" category
electronics_data = filter(lambda x: x['Category'] == "Electronics", Sales_data)

# Use map to calculate sales for each product
sales_values = map(lambda x: x['Price'] * x['Quantity_Sold'], electronics_data)

# Calculate the total sales for Electronics
total_electronics_sales = sum(sales_values)
print(f"Total Sales for Electronics: {total_electronics_sales}")

Total Sales for Electronics: 13100

## 3. Working With OOPs

**Design a simple Product class with attributes like name, price, and category.**

In Object-Oriented Programming (OOP) with Python, the concepts of class and object are fundamental:

**Class**: A class in Python is like a blueprint for creating objects. It defines a set of attributes and methods that the objects created from the class can have. Attributes are data members (variables) and methods are the functions that operate on these variables. A class is a way to bundle data and functionality together.

**Object**: An object is an instance of a class. When a class is defined, no memory is allocated until an object of that class is created. An object in Python encapsulates data and ways to manipulate that data. It has attributes (defined in the class) and methods to perform actions.

1. **Class Definition**
A class is a blueprint for creating objects. It encapsulates data for the object (attributes) and functions to manipulate that data (methods).

```
class ClassName:
    # Class body
```
2. **Attributes** (Instance Variables)
Attributes are variables that belong to the object. They are defined in the constructor method (__init__).

3. **The __init__ Method (Constructor)**
The __init__ method is a special method called a constructor. It is automatically invoked when an object is created.

4. **The self Parameter**
The self parameter is a reference to the current instance of the class. It is used to access variables and methods associated with the object.

```
class Product:
    def __init__(self, name, price, category):
        self.name = name # instance variable
        self.price = price # instance variable
        self.category = category # instance variable
```

**Design a simple Product class with attributes like name, price, and category.**

In [ ]:
class Product:
    def __init__(self, name, price, category):
        self.name = name
        self.price = price
        self.category = category

    def __str__(self):
        return f"Product Name: {self.name}, Price: {self.price} Rs, Category: {self.category}"

# 1. Define a class named `Product`.
#    - Classes in Python are used to create new objects (instances) that encapsulate data and functionality.

# 2. Define the `__init__` method (initializer).
#    - `__init__` is a special method that initializes (sets up) an object when it is created.
#    - `self` is the first parameter in every instance method. It refers to the current instance of the class (the object itself).
#    - `name`, `price`, and `category` are parameters used to initialize the attributes of the object.
#    - `self.name`, `self.price`, and `self.category` are instance variables (attributes) that store the data for each object.

# 3. Define the `__str__` method.
#    - `__str__` is another special method that returns a string representation of the object when `print()` or `str()` is called on it.
#    - It customizes how the object is printed as a string.
#    - In this case, it returns a formatted string containing the product's name, price, and category.

6.**Creating Objects (Instances)**
*     Objects are instances of a class. You create an object by calling the class as if it were a function.

7.**Accessing Attributes and Methods**
*     You can access attributes and methods of an object using the dot (.) notation.

In [ ]:

# Example of creating and using objects of the `Product` class:
# Create instances of the `Product` class
product1 = Product("Laptop", 80000, "Electronics")
product2 = Product("T-shirt", 500, "Apparel")

# Printing the objects will invoke the `__str__` method automatically
print(product1)
print(product2)
print()
print(product2.name)
print(product2.price)

Product Name: Laptop, Price: 80000 Rs, Category: Electronics
Product Name: T-shirt, Price: 500 Rs, Category: Apparel

T-shirt
500

8.**Methods**

* Methods are functions defined inside a class that operate on objects of that class.

* Now let's Extend the Product class by adding a method apply_discount which takes a percentage discount as an argument and adjusts the product's price accordingly. After applying the discount, the method should print the new price of the product.

In [ ]:
class Product:
    def __init__(self, name, price, category):
        self.name = name
        self.price = price
        self.category = category

    def __str__(self):
        return f"Product Name: {self.name}, Price: {self.price:.2f} Rs, Category: {self.category})"

    def apply_discount(self, discount_percentage):
        self.price *= (1 - discount_percentage / 100)
        print(f"New price of {self.name} after {discount_percentage}% discount: {self.price:.2f} Rs")

# Method (apply_discount):
#apply_discount(self, discount_percentage): Method to apply a discount to the product's price.
# Modifies self.price by reducing it based on the given discount_percentage.

# Example Usage
product = Product("Bluetooth Headphones", 1500.0, "Electronics")
print(product)
product.apply_discount(10)  # Applying a 10% discount

Product Name: Bluetooth Headphones, Price: 1500.00 Rs, Category: Electronics)
New price of Bluetooth Headphones after 10% discount: 1350.00 Rs

We can also try to create a SalesRecord class that manages the sales of various products. It should have methods to add a product sale and to calculate total sales. Each sale record should include the product, quantity sold, and calculate the total sale amount (price * quantity).

In [ ]:
class Product:
    def __init__(self, name, price, category):
        self.name = name
        self.price = price
        self.category = category

    def __str__(self):
        return f"Product Name: {self.name}, Price: {self.price:.2f} Rs, Category: {self.category}"

class SalesRecord:
    def __init__(self):
        self.sales = []  # Initialize an empty list to store sales records

    def add_sale(self, product, quantity):
        total_amount = product.price * quantity  # Calculate the total amount for this sale
        self.sales.append({"product": product, "quantity": quantity, "total_amount": total_amount})
        # Append a dictionary representing the sale to the `sales` list

    def calculate_total_sales(self):
        total_sales = sum(sale["total_amount"] for sale in self.sales)
        return total_sales  # Return the total sales amount

# Example Usage
sales_record = SalesRecord()  # Create an instance of the SalesRecord class

# Create instances of the Product class
product1 = Product("Organic Apple", 250, "Groceries")
product2 = Product("Yoga Mat", 400, "Sporting Goods")

# Add sales records to the sales_record instance
sales_record.add_sale(product1, 30)
sales_record.add_sale(product2, 10)

# Calculate and print the total sales amount recorded in the sales_record instance
total_sales_amount = sales_record.calculate_total_sales()
print(f"Total sales amount: {total_sales_amount:.2f} Rs")

Total sales amount: 11500.00 Rs

**Q14. Design a simple Product class with attributes like name, price, category, and stock (representing the number of items in stock). Extend the Product class by adding a method update_stock which takes a number as an argument and updates the product's stock by adding this number (which could be positive or negative). The method should then print the updated stock level. If the stock level goes below zero, the method should print a warning message indicating a stockout.**

In [ ]:
class Product:
    def __init__(self, name, price, category, stock):
        self.name = name
        self.price = price
        self.category = category
        self.stock = stock

    def __str__(self):
        return f"Product(Name: {self.name}, Price: {self.price} Rs, Category: {self.category}, Stock: {self.stock})"

    def update_stock(self, quantity):
        self.stock += quantity
        if self.stock < 0:
            print(f"Warning: Stockout for {self.name}. Current stock is {self.stock}.")
        else:
            print(f"Updated stock for {self.name} is now {self.stock}.")

# Example Usage
product = Product("Organic Apple", 200, "Groceries", 500)
print(product)
product.update_stock(-20)  # Selling 20 apples
product.update_stock(-35)  # Selling more than the current stock

Product(Name: Organic Apple, Price: 200 Rs, Category: Groceries, Stock: 500)
Updated stock for Organic Apple is now 480.
Updated stock for Organic Apple is now 445.